import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flashify AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <script async src="https://tally.so/widgets/embed.js"></script>
        </head>
        <body className={inter.className}>
          {children} 
        <Analytics />
        <SpeedInsights />
        </body>
      </html>
    </ClerkProvider>
  );
}
